---
- hosts: server
  become: yes


  tasks:
  - name: 'Update all packages'
    ansible.builtin.dnf:
      name: "*"
      state: latest
    tags: ['update_system']

  - name: 'Loading the overlay modules'
    modprobe:
      name: overlay
    ignore_errors: yes
  
  - name: 'Load the br_netfilter modules'
    modprobe:
      name: br_netfilter
    ignore_errors: yes
  
  - name: 'Ensure modules are loaded on boot'
    copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/containerd.conf

  - name: Create /etc/sysctl.d/kubernetes.conf file
    copy:
      content: |
        # Your sysctl settings for Kubernetes
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
      dest: /etc/sysctl.d/kubernetes.conf

  # - name: 'Set net.bridge.bridge-nf-call-ip6tables to 1'
  #   lineinfile:
  #     path: /etc/sysctl.d/kubernetes.conf
  #     line: 'net.bridge.bridge-nf-call-ip6tables = 1'
  #     state: present

  # - name: 'Set net.bridge.bridge-nf-call-iptables to 1'
  #   lineinfile:
  #     path: /etc/sysctl.d/kubernetes.conf
  #     line: 'net.bridge.bridge-nf-call-iptables = 1'
  #     state: present

  # - name: 'Set net.ipv4.ip_forward to 1'
  #   lineinfile:
  #     path: /etc/sysctl.d/kubernetes.conf
  #     line: 'net.ipv4.ip_forward = 1'
  #     state: present

  - name: 'Load sysctl settings'
    command: sysctl --system

  - name: 'Install yum-utils'
    yum:
      name: yum-utils
      state: present

  - name: 'Add Docker CE repository'
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: 'Install containerd.io'
    yum:
      name: containerd.io
      state: present
  
  - name: 'Create /etc/containerd directory'
    file:
      path: /etc/containerd
      state: directory

  - name: 'Generate default containerd configuration'
    command: containerd config default
    args:
      creates: /etc/containerd/config.toml

  - name: 'Ensure cgroupDriver is set to systemd in containerd config'
    lineinfile:
      path: /etc/containerd/config.toml
      regexp: '^(\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\].*SystemdCgroup\s*=\s*).*'
      line: '\1true'
      backup: yes      

  - name: 'Restart containerd service'
    systemd:
      name: containerd
      state: restarted

  - name: 'Add Kubernetes repository'
    # blockinfile:
    #   path: /etc/yum.repos.d/kubernetes.repo
    #   block: |
    #     [kubernetes]
    #     name=Kubernetes
    #     baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    #     enabled=1
    #     gpgcheck=0
    # create: yes
    copy:
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=0
      dest: /etc/yum.repos.d/kubernetes.repo      

  - name: 'Install kubelet, kubeadm, and kubectl'
    yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present

  - name: 'Disable swap'
    command: swapoff -a

  - name: 'Comment out swap entry in /etc/fstab'
    replace:
      path: /etc/fstab
      regexp: '^(\S+\s+swap\s+\S+\s+\S+\s+\S+\s+\S+)$'
      replace: '#\1'

  - name: 'Enable and start kubelet service'
    systemd:
      name: kubelet
      enabled: yes
      state: started

  - name: 'Reload systemd'
    command: systemctl daemon-reload

  - name: 'Restart kubelet service'
    systemd:
      name: kubelet
      state: restarted  

