---
# tasks file for tomcat
  - name: 'Update all packages'
    ansible.builtin.dnf:
      name: "*"
      state: latest
    tags: ['update_system']

  - name: 'Install Java Development Kit'
    ansible.builtin.dnf:
      name: java-1.8.0-openjdk
      state: present
    tags: ['install_jdk']

  - name: 'Add Tomcat Group'
    group:
      name: tomcat
      state: present
    tags: ['add_grp']

  - name: 'Add Tomcat User'
    user:
      name: tomcat
      comment: "Tomcat User"
      shell: /bin/false
      home: /opt/tomcat
      group: tomcat
    tags: ['add_usr']

  - name: 'Download Apache Tomcat tarball'
    ansible.builtin.get_url:
      url: 'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz'
      dest: /tmp/apache-tomcat-8.5.96.tar.gz
    tags: ['download_tomcat_tar']

  - name: 'Create /opt/tomcat directory'
    file:
      path: /opt/tomcat
      state: directory
      mode: '0755'
      owner: tomcat
      group: tomcat
    tags: ['makedir']

  - name: 'Extract Tomcat tarball'
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-8.5.96.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      creates: /opt/tomcat/bin/catalina.sh
    tags: ['unarchive']

  - name: 'Change group ownership of /opt/tomcat'
    ansible.builtin.file:
      path: /opt/tomcat
      recurse: yes
      owner: tomcat
      group: tomcat
      state: directory

  - name: 'Change permissions of /opt/tomcat/conf'
    ansible.builtin.file:
      path: /opt/tomcat/conf
      recurse: yes
      state: directory
      mode: 'g+rx'
    tags: ['permissions']

  - name: 'Change ownership of /opt/tomcat subdirectories'
    ansible.builtin.file:
      path: "/opt/tomcat/{{ item }}"
      recurse: yes
      state: directory
      owner: tomcat
    loop:
      - webapps
      - work
      - temp
      - logs
    tags: ['change_pre_in_loop']


  - name: Start Tomcat service
    ansible.builtin.systemd:
      name: tomcat
      state: started
    notify: Restart tomcat
    tags: ['restart-tomcat']

  - name: 'Create tomcat.service file'
    ansible.builtin.template:
      src: tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
    notify: Reload systemd
    tags: ['reload']
