---
# tasks file for maven

  - name: 'Update all packages'
    ansible.builtin.dnf:
      name: "*"
      state: latest
    tags: ['update_system']

  - name: 'Install Java Development Kit'
    ansible.builtin.dnf:
      name: java-1.8.0-openjdk
      state: present
    tags: ['install_jdk']

  - name: 'Download Apache Maven tarball'
    ansible.builtin.get_url:
      url: 'https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz'
      dest: /tmp/apache-maven-3.9.5-bin.tar.gz
    tags: ['download_maven_tar']


  # - name: 'Create /opt/maven directory'
  #   file:
  #     path: /opt/maven
  #     state: directory
  #     mode: '0755'
  #     owner: root
  #     group: root
  #   tags: ['makedir']

  - name: 'Extract Maven tarball'
    ansible.builtin.unarchive:
      src: /tmp/apache-maven-3.9.5-bin.tar.gz
      dest: /opt/
      remote_src: yes
    tags: ['unarchive']

  - name: Set up Maven alternatives
    ansible.builtin.alternatives:
      name: maven
      path: /opt/apache-maven-3.9.5/bin/mvn
      priority: 1001
      state: present
